- env_id: Endless-v0
  env_configs:
    carla_map: Town01
    num_zombie_vehicles: [80, 160]
    num_zombie_walkers: [80, 160]
    weather_group: train
- env_id: Endless-v0
  env_configs:
    carla_map: Town03
    num_zombie_vehicles: [40, 100]
    num_zombie_walkers: [40, 100]
    weather_group: train
- env_id: Endless-v0
  env_configs:
    carla_map: Town04
    num_zombie_vehicles: [100, 200]
    num_zombie_walkers: [40, 120]
    weather_group: train
- env_id: Endless-v0
  env_configs:
    carla_map: Town06
    num_zombie_vehicles: [80, 160]
    num_zombie_walkers: [40, 120]
    weather_group: train
