name: mile
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
- python=3.8.15
- pytorch=1.11.0
- torchvision=0.12.0
- cudatoolkit=11.3
- ffmpeg=4.3.1
- pip=21.0.1
- pip:
    - pytorch-lightning=1.8.6
    - torchmetrics=0.10.0
    - wandb==0.13.9
    - timm==0.5.4
    - gym=0.17.2
    - gym-box2d=0.17.2
    - hydra-core=1.1.1
    - scipy=1.5.2
    - fvcore=0.1.2.post20201122
    - h5py=2.10.0
    - setuptools=49.6.0
    - opencv-python==4.5.1.48
    - moviepy==1.0.3
    - stable-baselines3==0.8.0
    - importlib-resources==3.0.0
    - imgaug==0.4.0
    - notebook==6.4.4
    - scikit-video==1.1.11
